import{useState}from'react';import{useQuery}from'@tanstack/react-query';import ReactECharts from'echarts-for-react';import{api,fa,faDate}from'../lib/api';import JalaliDate,{todayIso}from'../components/JalaliDate';import Loading from'../components/Loading';
type Totals={reports:number,totalPeople:number,contacted:number,notContacted:number,ok:number,maybe:number,no:number,noAnswer:number,contactRate:number,okRate:number};type Data={totals:Totals;previous:Totals;trend:{date:string,totalPeople:number;contacted:number;ok:number;maybe:number;no:number;noAnswer:number}[];agents:{agentId:number;agentName:string;reports:number;totalPeople:number;contacted:number;ok:number;maybe:number;no:number;noAnswer:number}[]};
export default function ManagerPage(){const[from,setFrom]=useState(todayIso());const[to,setTo]=useState(todayIso());const[context,setContext]=useState<'OPERATIONAL'|'OFFICIAL'>('OPERATIONAL');const[supervisor,setSupervisor]=useState('');const[agent,setAgent]=useState('');const filters=useQuery({queryKey:['dashboard-filters'],queryFn:()=>api<{supervisors:{id:number;name:string}[];agents:{id:number;name:string;supervisorId?:number}[]}>('/api/v1/dashboard/filters')});const suffix=`&supervisorId=${supervisor}&agentId=${agent}`.replace(/&(?:supervisorId|agentId)=(&|$)/g,'$1');const q=useQuery({queryKey:['dashboard',from,to,context,supervisor,agent],queryFn:()=>api<Data>(`/api/v1/dashboard?from=${from}&to=${to}&context=${context}${suffix}`)});
 const d=q.data,t=d?.totals;const cards=[['کل افراد',t?.totalPeople,'users'],['تماس‌گرفته',t?.contacted,'phone'],['نتیجه OK',t?.ok,'ok'],['نرخ تماس',t?`${fa(t.contactRate)}٪`:0,'rate'],['در انتظار/گزارش',t?.reports,'doc']];
 const line={tooltip:{trigger:'axis'},legend:{data:['کل افراد','تماس‌گرفته','OK']},grid:{left:42,right:18,top:48,bottom:32},xAxis:{type:'category',data:d?.trend.map(x=>faDate(x.date))},yAxis:{type:'value'},series:[{name:'کل افراد',type:'line',smooth:true,data:d?.trend.map(x=>x.totalPeople),itemStyle:{color:'#123a63'}},{name:'تماس‌گرفته',type:'line',smooth:true,data:d?.trend.map(x=>x.contacted),itemStyle:{color:'#f4b51b'}},{name:'OK',type:'line',smooth:true,data:d?.trend.map(x=>x.ok),itemStyle:{color:'#20a36a'}}]};
 const pie={tooltip:{trigger:'item'},legend:{bottom:0},series:[{type:'pie',radius:['48%','72%'],label:{formatter:'{b}\\n{c}'},data:[{name:'OK',value:t?.ok||0,itemStyle:{color:'#20a36a'}},{name:'شاید',value:t?.maybe||0,itemStyle:{color:'#f4b51b'}},{name:'NO',value:t?.no||0,itemStyle:{color:'#e35d6a'}},{name:'جواب نداد',value:t?.noAnswer||0,itemStyle:{color:'#7c8da5'}}]}]};
 function download(ext:string){window.open(`/api/v1/exports/reports.${ext}?from=${from}&to=${to}&context=${context}${suffix}`)}
 return <div className="page manager"><header className="page-head"><div><span className="eyebrow">داشبورد مدیریت</span><h1>نبض امروز کال‌سنتر</h1><p>اطلاعات به‌محض ارسال اپراتورها به‌روزرسانی می‌شود.</p></div><div className="live"><i/>به‌روز و لحظه‌ای</div></header>
 <section className="filters"><div className="segmented"><button className={context==='OPERATIONAL'?'active':''} onClick={()=>setContext('OPERATIONAL')}>نمای لحظه‌ای</button><button className={context==='OFFICIAL'?'active':''} onClick={()=>setContext('OFFICIAL')}>آمار قطعی</button></div><label>از <JalaliDate value={from} onChange={setFrom} max={false}/></label><label>تا <JalaliDate value={to} onChange={setTo}/></label><label>ناظر<select value={supervisor} onChange={e=>{setSupervisor(e.target.value);setAgent('')}}><option value="">همه ناظران</option>{filters.data?.supervisors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>اپراتور<select value={agent} onChange={e=>setAgent(e.target.value)}><option value="">همه اپراتورها</option>{filters.data?.agents.filter(x=>!supervisor||x.supervisorId===Number(supervisor)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="export"><button onClick={()=>download('xlsx')}>خروجی Excel</button><button onClick={()=>download('csv')}>CSV</button></div></section>
 {q.isLoading?<Loading/>:<>{<div className="kpis">{cards.map(([l,v,c])=><article className={String(c)} key={String(l)}><span>{l}</span><b>{typeof v==='number'?fa(v):v}</b><small>دوره قبل: {fa((d?.previous as any)?.[l==='کل افراد'?'totalPeople':l==='تماس‌گرفته'?'contacted':l==='نتیجه OK'?'ok':'reports']||0)}</small></article>)}</div>}
 <div className="charts"><section><div className="section-title"><b>روند عملکرد</b><span>مقایسه روزانه تماس‌ها</span></div><ReactECharts option={line} style={{height:310}}/></section><section><div className="section-title"><b>توزیع نتایج</b><span>از مجموع تماس‌های ثبت‌شده</span></div><ReactECharts option={pie} style={{height:310}}/></section></div>
 <section className="table-card"><div className="section-title"><b>عملکرد اپراتورها</b><span>{fa(d?.agents.length||0)} اپراتور فعال در بازه</span></div><div className="table-scroll"><table><thead><tr><th>اپراتور</th><th>گزارش</th><th>کل افراد</th><th>تماس</th><th>OK</th><th>شاید</th><th>NO</th><th>جواب نداد</th></tr></thead><tbody>{d?.agents.map(a=><tr key={a.agentId}><td><b>{a.agentName}</b></td><td>{fa(a.reports)}</td><td>{fa(a.totalPeople)}</td><td>{fa(a.contacted)}</td><td className="green">{fa(a.ok)}</td><td>{fa(a.maybe)}</td><td>{fa(a.no)}</td><td>{fa(a.noAnswer)}</td></tr>)}</tbody></table></div></section></>}</div>}
