import{useState}from'react';import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';import{api,fa,faDate,Report}from'../lib/api';import Loading from'../components/Loading';
export default function SupervisorPage(){const qc=useQueryClient();const q=useQuery({queryKey:['pending'],queryFn:()=>api<Report[]>('/api/v1/supervisor/reports/pending')});const[selected,setSelected]=useState<Report>();const[edit,setEdit]=useState<Report>();const[reason,setReason]=useState('');
 const review=useMutation({mutationFn:()=>api<Report>(`/api/v1/supervisor/reports/${edit!.id}/approve`,{method:'POST',body:JSON.stringify({...edit,correctionReason:reason})}),onSuccess:()=>{setSelected(undefined);setEdit(undefined);setReason('');qc.invalidateQueries({queryKey:['pending']})}});
 function choose(r:Report){setSelected(r);setEdit({...r})}const changed=selected&&edit&&['totalPeople','contactedCount','okCount','maybeCount','noCount','noAnswerCount','notes'].some(k=>selected[k as keyof Report]!==edit[k as keyof Report]);
 return <div className="page"><header className="page-head"><div><span className="eyebrow">پنل ناظر</span><h1>صف بررسی گزارش‌ها</h1><p>گزارش‌های تیم خود را کنترل و نهایی کنید.</p></div><div className="pending-count"><b>{fa(q.data?.length||0)}</b><span>در انتظار بررسی</span></div></header>
 {q.isLoading?<Loading/>:!q.data?.length?<div className="empty"><b>همه‌چیز مرتب است</b><span>گزارشی در انتظار بررسی نیست.</span></div>:<div className="review-layout"><section className="queue">{q.data.map(r=><button className={selected?.id===r.id?'active':''} key={r.id} onClick={()=>choose(r)}><div className="avatar">{r.agentName.slice(0,1)}</div><div><b>{r.agentName}</b><small>{faDate(r.reportDate)} · {fa(r.contactedCount)} تماس</small></div><span>›</span></button>)}</section>
 {edit?<section className="review-card"><div className="review-title"><div><b>{edit.agentName}</b><span>{faDate(edit.reportDate)}</span></div><span className="status SUBMITTED">در انتظار تأیید</span></div><div className="review-fields">{([['totalPeople','کل افراد'],['contactedCount','تماس‌گرفته'],['okCount','OK'],['maybeCount','شاید'],['noCount','NO'],['noAnswerCount','جواب نداد']]as const).map(([k,l])=><label key={k}>{l}<input inputMode="numeric" value={edit[k]} onChange={e=>setEdit({...edit,[k]:Number(e.target.value)})}/></label>)}</div>
 <label className="notes">توضیحات<textarea value={edit.notes||''} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>{changed&&<label className="notes required">دلیل اصلاح<textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="دلیل تغییر اعداد را ثبت کنید…"/></label>}
 {review.error&&<div className="error">{review.error.message}</div>}<button className="primary wide" disabled={!!changed&&!reason.trim()||review.isPending} onClick={()=>review.mutate()}>{changed?'اصلاح و تأیید نهایی':'تأیید گزارش'} ✓</button></section>:<div className="empty compact">یک گزارش را برای بررسی انتخاب کنید.</div>}</div>}</div>}
