import{useEffect,useMemo,useState}from'react';import{useQuery}from'@tanstack/react-query';import ReactECharts from'echarts-for-react';import{api,apiUrl,fa,faDate,faDateTime,Report,statusLabel}from'../lib/api';import JalaliDate,{todayIso}from'../components/JalaliDate';import Loading from'../components/Loading';
type Totals={reports:number,totalPeople:number,contacted:number,notContacted:number,ok:number,maybe:number,no:number,noAnswer:number,attendees:number,contactRate:number,okRate:number,showUpRate:number};type Agent={agentId:number;agentName:string;reports:number;totalPeople:number;contacted:number;ok:number;maybe:number;no:number;noAnswer:number;attendees:number;showUpRate:number};type SchoolRow={school:string;reports:number;totalPeople:number;contacted:number;ok:number;attendees:number;showUpRate:number};
type Data={totals:Totals;previous:Totals;schools:SchoolRow[];trend:{date:string;totalPeople:number;contacted:number;ok:number;maybe:number;no:number;noAnswer:number;attendees:number}[];agents:Agent[];reports:Report[]};
export default function ManagerPage(){
 const[from,setFrom]=useState(todayIso()),[to,setTo]=useState(todayIso()),[context,setContext]=useState<'OPERATIONAL'|'OFFICIAL'>('OPERATIONAL'),[supervisor,setSupervisor]=useState(''),[agent,setAgent]=useState(''),[visible,setVisible]=useState<number[]>([]);
 const filters=useQuery({queryKey:['dashboard-filters'],queryFn:()=>api<{supervisors:{id:number;name:string}[];agents:{id:number;name:string;supervisorId?:number}[]}>('/api/v1/dashboard/filters')});
 const suffix=`&supervisorId=${supervisor}&agentId=${agent}`.replace(/&(?:supervisorId|agentId)=(&|$)/g,'$1'),q=useQuery({queryKey:['dashboard',from,to,context,supervisor,agent],queryFn:()=>api<Data>(`/api/v1/dashboard?from=${from}&to=${to}&context=${context}${suffix}`)});
 const d=q.data,t=d?.totals;useEffect(()=>{if(d)setVisible(d.agents.map(a=>a.agentId))},[d]);
 const cards=[['حاضرین در کلاس',t?.attendees,'attendees',d?.previous.attendees],['کل افراد',t?.totalPeople,'users',d?.previous.totalPeople],['تماس‌گرفته',t?.contacted,'phone',d?.previous.contacted],['تماس‌نگرفته',t?.notContacted,'doc',d?.previous.notContacted],['نتیجه OK',t?.ok,'ok',d?.previous.ok],['نرخ تماس',t?`${fa(t.contactRate)}٪`:0,'rate',d?.previous.contactRate]];
 const line={tooltip:{trigger:'axis'},legend:{top:0},grid:{left:20,right:18,top:52,bottom:60,containLabel:true},xAxis:{type:'category',axisLabel:{rotate:(d?.trend.length||0)>5?30:0},data:d?.trend.map(x=>faDate(x.date))},yAxis:{type:'value'},series:[{name:'کل افراد',type:'bar',data:d?.trend.map(x=>x.totalPeople),itemStyle:{color:'#dce8f3'}},{name:'تماس‌گرفته',type:'line',smooth:true,data:d?.trend.map(x=>x.contacted),itemStyle:{color:'#f4b51b'}},{name:'OK',type:'line',smooth:true,data:d?.trend.map(x=>x.ok),itemStyle:{color:'#20a36a'}}]};
 const shown=d?.agents.filter(a=>visible.includes(a.agentId))||[];
 const compare={tooltip:{trigger:'axis'},legend:{top:0},grid:{left:20,right:15,top:48,bottom:70,containLabel:true},xAxis:{type:'category',axisLabel:{rotate:25},data:shown.map(a=>a.agentName)},yAxis:{type:'value'},series:[{name:'تماس',type:'bar',data:shown.map(a=>a.contacted),itemStyle:{color:'#1b568d'}},{name:'OK',type:'bar',data:shown.map(a=>a.ok),itemStyle:{color:'#20a36a'}}]};
 const pie={tooltip:{trigger:'item'},legend:{bottom:0},series:[{type:'pie',radius:['43%','72%'],avoidLabelOverlap:true,label:{position:'inside',formatter:'{b}\\n{c}',fontSize:10,color:'#fff'},labelLine:{show:false},data:[{name:'OK',value:t?.ok||0,itemStyle:{color:'#20a36a'}},{name:'شاید',value:t?.maybe||0,itemStyle:{color:'#f4b51b'}},{name:'NO',value:t?.no||0,itemStyle:{color:'#e35d6a'}},{name:'جواب نداد',value:t?.noAnswer||0,itemStyle:{color:'#7c8da5'}}]}]};
 function download(ext:string){window.open(apiUrl(`/api/v1/exports/reports.${ext}?from=${from}&to=${to}&context=${context}${suffix}`))}
 return <div className="page manager"><header className="page-head"><div><span className="eyebrow">داشبورد مدیریت</span><h1>تصویر کامل کال‌سنتر</h1><p>آمار لحظه‌ای، مقایسه اپراتورها و جزئیات تمام گزارش‌ها.</p></div><div className="live"><i/>به‌روز و لحظه‌ای</div></header>
 <section className="filters"><div className="segmented"><button className={context==='OPERATIONAL'?'active':''} onClick={()=>setContext('OPERATIONAL')}>نمای لحظه‌ای</button><button className={context==='OFFICIAL'?'active':''} onClick={()=>setContext('OFFICIAL')}>آمار قطعی</button></div><label>از <JalaliDate value={from} onChange={setFrom} max={false}/></label><label>تا <JalaliDate value={to} onChange={setTo}/></label><label>ناظر<select value={supervisor} onChange={e=>{setSupervisor(e.target.value);setAgent('')}}><option value="">همه ناظران</option>{filters.data?.supervisors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>اپراتور<select value={agent} onChange={e=>setAgent(e.target.value)}><option value="">همه اپراتورها</option>{filters.data?.agents.filter(x=>!supervisor||x.supervisorId===Number(supervisor)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="export"><button onClick={()=>download('xlsx')}>Excel</button><button onClick={()=>download('csv')}>CSV</button></div></section>
 {q.isLoading?<Loading/>:<><div className="kpis">{cards.map(([l,v,c,p])=><article className={String(c)} key={String(l)}><span>{l}</span><b>{typeof v==='number'?fa(v):v}</b><small>دوره قبل: {fa(Number(p||0))}</small></article>)}</div>
 <div className="charts"><section><div className="section-title"><b>روند روزانه</b><span>ستونی و خطی</span></div><ReactECharts option={line} style={{height:330}}/></section><section><div className="section-title"><b>توزیع نتایج</b><span>{fa(t?.contacted||0)} تماس</span></div><ReactECharts option={pie} style={{height:330}}/></section></div>
 <section className="table-card comparison"><div className="section-title"><b>مقایسه اپراتورها</b><span>برای حذف یا نمایش هر نفر روی نام او بزنید</span></div><div className="operator-chips">{d?.agents.map(a=><button className={visible.includes(a.agentId)?'active':''} onClick={()=>setVisible(v=>v.includes(a.agentId)?v.filter(x=>x!==a.agentId):[...v,a.agentId])} key={a.agentId}>✓ {a.agentName}</button>)}</div><ReactECharts option={compare} style={{height:330}}/></section>
 <section className="table-card"><div className="section-title"><b>عملکرد اپراتورها</b><span>{fa(d?.agents.length||0)} اپراتور</span></div><div className="table-scroll"><table><thead><tr><th>اپراتور</th><th>گزارش</th><th>کل</th><th>تماس</th><th>نرخ تماس</th><th>OK</th><th>شاید</th><th>NO</th><th>جواب نداد</th><th>حاضرین</th><th>نرخ حضور</th></tr></thead><tbody>{d?.agents.map(a=><tr key={a.agentId}><td><b>{a.agentName}</b></td><td>{fa(a.reports)}</td><td>{fa(a.totalPeople)}</td><td>{fa(a.contacted)}</td><td>{fa(a.totalPeople?a.contacted*100/a.totalPeople:0)}٪</td><td className="green">{fa(a.ok)}</td><td>{fa(a.maybe)}</td><td>{fa(a.no)}</td><td>{fa(a.noAnswer)}</td><td className="green"><b>{fa(a.attendees)}</b></td><td>{a.ok?fa(a.showUpRate)+'٪':'—'}</td></tr>)}</tbody></table></div></section>

 {/* Per-school comparison: the same outcomes grouped by who was called rather than who
     called. This is what tells a manager which schools actually convert into attendance. */}
 <section className="table-card"><div className="section-title"><b>عملکرد به تفکیک مدرسه</b><span>{fa(d?.schools?.length||0)} مدرسه</span></div>
 <div className="table-scroll"><table><thead><tr><th>مدرسه</th><th>گزارش</th><th>کل افراد</th><th>تماس‌گرفته</th><th>OK</th><th>حاضرین</th><th>نرخ حضور</th></tr></thead>
 <tbody>{d?.schools?.length?d.schools.map(sc=><tr key={sc.school}><td><b>{sc.school}</b></td><td>{fa(sc.reports)}</td><td>{fa(sc.totalPeople)}</td><td>{fa(sc.contacted)}</td><td className="green">{fa(sc.ok)}</td><td><b>{fa(sc.attendees)}</b></td><td>{sc.ok?fa(sc.showUpRate)+'٪':'—'}</td></tr>)
  :<tr><td colSpan={7} className="empty-cell">هنوز مدرسه‌ای در گزارش‌ها ثبت نشده است.</td></tr>}</tbody></table></div></section>
 <section className="table-card report-ledger"><div className="section-title"><b>دفتر گزارش‌ها</b><span>زمان ارسال و تأیید هر گزارش</span></div><div className="table-scroll"><table><thead><tr><th>اپراتور</th><th>عنوان</th><th>تاریخ گزارش</th><th>وضعیت</th><th>ارسال</th><th>تأیید</th><th>تماس / کل</th></tr></thead><tbody>{d?.reports.map(r=><tr key={r.id}><td><b>{r.agentName}</b></td><td>{r.reportLabel||'—'}</td><td>{faDate(r.reportDate)}</td><td><span className={'status '+r.status}>{statusLabel[r.status]}</span></td><td>{faDateTime(r.submittedAt)}</td><td>{faDateTime(r.reviewedAt)}</td><td>{fa(r.contactedCount)} / {fa(r.totalPeople)}</td></tr>)}</tbody></table></div></section></>}</div>
}
